/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface OracleManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeOracle"
      | "authorizedOracles"
      | "getAuthorizedOracles"
      | "getOracleCount"
      | "isAuthorizedOracle"
      | "oraclesList"
      | "owner"
      | "revokeOracle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OracleAuthorized" | "OracleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorizedOracles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oraclesList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeOracle",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizedOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oraclesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeOracle",
    data: BytesLike
  ): Result;
}

export namespace OracleAuthorizedEvent {
  export type InputTuple = [oracle: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [oracle: string, timestamp: bigint];
  export interface OutputObject {
    oracle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRevokedEvent {
  export type InputTuple = [oracle: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [oracle: string, timestamp: bigint];
  export interface OutputObject {
    oracle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleManager extends BaseContract {
  connect(runner?: ContractRunner | null): OracleManager;
  waitForDeployment(): Promise<this>;

  interface: OracleManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOracles: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAuthorizedOracles: TypedContractMethod<[], [string[]], "view">;

  getOracleCount: TypedContractMethod<[], [bigint], "view">;

  isAuthorizedOracle: TypedContractMethod<
    [oracle: AddressLike],
    [boolean],
    "view"
  >;

  oraclesList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  revokeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOracles"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAuthorizedOracles"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOracleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedOracle"
  ): TypedContractMethod<[oracle: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oraclesList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OracleAuthorized"
  ): TypedContractEvent<
    OracleAuthorizedEvent.InputTuple,
    OracleAuthorizedEvent.OutputTuple,
    OracleAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRevoked"
  ): TypedContractEvent<
    OracleRevokedEvent.InputTuple,
    OracleRevokedEvent.OutputTuple,
    OracleRevokedEvent.OutputObject
  >;

  filters: {
    "OracleAuthorized(address,uint256)": TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;
    OracleAuthorized: TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;

    "OracleRevoked(address,uint256)": TypedContractEvent<
      OracleRevokedEvent.InputTuple,
      OracleRevokedEvent.OutputTuple,
      OracleRevokedEvent.OutputObject
    >;
    OracleRevoked: TypedContractEvent<
      OracleRevokedEvent.InputTuple,
      OracleRevokedEvent.OutputTuple,
      OracleRevokedEvent.OutputObject
    >;
  };
}
