/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PESContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SCORE_THRESHOLD"
      | "agreementCounter"
      | "agreements"
      | "changeGovernanceMode"
      | "createAgreement"
      | "createAgreementWithInvestor"
      | "deactivateAgreement"
      | "executePayment"
      | "financialManager"
      | "getAgreement"
      | "getAgreementScore"
      | "getPaymentRecord"
      | "investInAgreement"
      | "oracleManager"
      | "owner"
      | "paymentCounter"
      | "payments"
      | "recordAudit"
      | "recordAuditV3"
      | "relayer"
      | "requestPayment"
      | "setFinancialManager"
      | "setOracleManager"
      | "setRelayer"
      | "setTechnicalManager"
      | "submitValidatedBatch"
      | "technicalManager"
      | "withdrawExcessHBAR"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementCreated"
      | "AuditRecorded"
      | "AuditRecordedV3"
      | "GovernanceModeChanged"
      | "InvestmentReceived"
      | "PaymentApproved"
      | "PaymentExecuted"
      | "PaymentRequested"
      | "ValidatedBatchSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "SCORE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreementCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeGovernanceMode",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreementWithInvestor",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "financialManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreementScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investInAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAudit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAuditV3",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestPayment",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFinancialManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTechnicalManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitValidatedBatch",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "technicalManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawExcessHBAR",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "SCORE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agreementCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeGovernanceMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAgreementWithInvestor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "financialManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreementScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investInAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAuditV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFinancialManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTechnicalManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitValidatedBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "technicalManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawExcessHBAR",
    data: BytesLike
  ): Result;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    agreementHash: BytesLike,
    producer: AddressLike,
    investor: AddressLike,
    baseValue: BigNumberish,
    hectares: BigNumberish,
    governanceMode: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    agreementHash: string,
    producer: string,
    investor: string,
    baseValue: bigint,
    hectares: bigint,
    governanceMode: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    agreementHash: string;
    producer: string;
    investor: string;
    baseValue: bigint;
    hectares: bigint;
    governanceMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditRecordedEvent {
  export type InputTuple = [auditHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [auditHash: string, timestamp: bigint];
  export interface OutputObject {
    auditHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditRecordedV3Event {
  export type InputTuple = [
    auditHash: BytesLike,
    timestamp: BigNumberish,
    hcsTransactionId: string,
    hfsFileId: string
  ];
  export type OutputTuple = [
    auditHash: string,
    timestamp: bigint,
    hcsTransactionId: string,
    hfsFileId: string
  ];
  export interface OutputObject {
    auditHash: string;
    timestamp: bigint;
    hcsTransactionId: string;
    hfsFileId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceModeChangedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    oldMode: BigNumberish,
    newMode: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    oldMode: bigint,
    newMode: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    oldMode: bigint;
    newMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentReceivedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish,
    totalInvested: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    investor: string,
    amount: bigint,
    totalInvested: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    investor: string;
    amount: bigint;
    totalInvested: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentApprovedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    producer: AddressLike,
    auditHash: BytesLike,
    investor: AddressLike,
    amount: BigNumberish,
    score: BigNumberish,
    hcsTransactionId: string,
    hfsFileId: string
  ];
  export type OutputTuple = [
    agreementId: bigint,
    producer: string,
    auditHash: string,
    investor: string,
    amount: bigint,
    score: bigint,
    hcsTransactionId: string,
    hfsFileId: string
  ];
  export interface OutputObject {
    agreementId: bigint;
    producer: string;
    auditHash: string;
    investor: string;
    amount: bigint;
    score: bigint;
    hcsTransactionId: string;
    hfsFileId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    agreementId: BigNumberish,
    producer: AddressLike,
    amount: BigNumberish,
    hcsTransactionId: string,
    hfsFileId: string
  ];
  export type OutputTuple = [
    paymentId: bigint,
    agreementId: bigint,
    producer: string,
    amount: bigint,
    hcsTransactionId: string,
    hfsFileId: string
  ];
  export interface OutputObject {
    paymentId: bigint;
    agreementId: bigint;
    producer: string;
    amount: bigint;
    hcsTransactionId: string;
    hfsFileId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRequestedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    producer: AddressLike,
    amount: BigNumberish,
    auditHash: BytesLike
  ];
  export type OutputTuple = [
    agreementId: bigint,
    producer: string,
    amount: bigint,
    auditHash: string
  ];
  export interface OutputObject {
    agreementId: bigint;
    producer: string;
    amount: bigint;
    auditHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatedBatchSubmittedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    oracle: AddressLike,
    auditHash: BytesLike,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    oracle: string,
    auditHash: string,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    oracle: string;
    auditHash: string;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PESContract extends BaseContract {
  connect(runner?: ContractRunner | null): PESContract;
  waitForDeployment(): Promise<this>;

  interface: PESContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SCORE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  agreementCounter: TypedContractMethod<[], [bigint], "view">;

  agreements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        agreementHash: string;
        producer: string;
        investor: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
        lastScore: bigint;
        lastAuditHash: string;
        lastUpdateTimestamp: bigint;
        governanceMode: bigint;
        totalInvested: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;

  changeGovernanceMode: TypedContractMethod<
    [_agreementId: BigNumberish, _newMode: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAgreement: TypedContractMethod<
    [
      _agreementHash: BytesLike,
      _producer: AddressLike,
      _baseValue: BigNumberish,
      _hectares: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createAgreementWithInvestor: TypedContractMethod<
    [
      _agreementHash: BytesLike,
      _producer: AddressLike,
      _investor: AddressLike,
      _baseValue: BigNumberish,
      _hectares: BigNumberish,
      _governanceMode: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deactivateAgreement: TypedContractMethod<
    [_agreementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executePayment: TypedContractMethod<
    [
      _agreementId: BigNumberish,
      _amount: BigNumberish,
      _auditHash: BytesLike,
      _score: BigNumberish,
      _hcsTransactionId: string,
      _hfsFileId: string
    ],
    [void],
    "nonpayable"
  >;

  financialManager: TypedContractMethod<[], [string], "view">;

  getAgreement: TypedContractMethod<
    [_agreementId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        agreementHash: string;
        producer: string;
        investor: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
        lastScore: bigint;
        lastAuditHash: string;
        lastUpdateTimestamp: bigint;
        governanceMode: bigint;
        totalInvested: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;

  getAgreementScore: TypedContractMethod<
    [_agreementId: BigNumberish],
    [bigint],
    "view"
  >;

  getPaymentRecord: TypedContractMethod<
    [_paymentId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        agreementId: bigint;
        producer: string;
        investor: string;
        amount: bigint;
        auditHash: string;
        score: bigint;
        timestamp: bigint;
        hcsTransactionId: string;
        hfsFileId: string;
      }
    ],
    "view"
  >;

  investInAgreement: TypedContractMethod<
    [_agreementId: BigNumberish],
    [void],
    "payable"
  >;

  oracleManager: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentCounter: TypedContractMethod<[], [bigint], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        agreementId: bigint;
        producer: string;
        investor: string;
        amount: bigint;
        auditHash: string;
        score: bigint;
        timestamp: bigint;
        hcsTransactionId: string;
        hfsFileId: string;
      }
    ],
    "view"
  >;

  recordAudit: TypedContractMethod<
    [_auditHash: BytesLike],
    [void],
    "nonpayable"
  >;

  recordAuditV3: TypedContractMethod<
    [_auditHash: BytesLike, _hcsTransactionId: string, _hfsFileId: string],
    [void],
    "nonpayable"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  requestPayment: TypedContractMethod<
    [_agreementId: BigNumberish, _auditHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setFinancialManager: TypedContractMethod<
    [_financialManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setOracleManager: TypedContractMethod<
    [_oracleManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  setTechnicalManager: TypedContractMethod<
    [_technicalManager: AddressLike],
    [void],
    "nonpayable"
  >;

  submitValidatedBatch: TypedContractMethod<
    [_agreementId: BigNumberish, _auditHash: BytesLike, _score: BigNumberish],
    [void],
    "nonpayable"
  >;

  technicalManager: TypedContractMethod<[], [string], "view">;

  withdrawExcessHBAR: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SCORE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agreementCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        agreementHash: string;
        producer: string;
        investor: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
        lastScore: bigint;
        lastAuditHash: string;
        lastUpdateTimestamp: bigint;
        governanceMode: bigint;
        totalInvested: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "changeGovernanceMode"
  ): TypedContractMethod<
    [_agreementId: BigNumberish, _newMode: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      _agreementHash: BytesLike,
      _producer: AddressLike,
      _baseValue: BigNumberish,
      _hectares: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createAgreementWithInvestor"
  ): TypedContractMethod<
    [
      _agreementHash: BytesLike,
      _producer: AddressLike,
      _investor: AddressLike,
      _baseValue: BigNumberish,
      _hectares: BigNumberish,
      _governanceMode: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateAgreement"
  ): TypedContractMethod<[_agreementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<
    [
      _agreementId: BigNumberish,
      _amount: BigNumberish,
      _auditHash: BytesLike,
      _score: BigNumberish,
      _hcsTransactionId: string,
      _hfsFileId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "financialManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [_agreementId: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        agreementHash: string;
        producer: string;
        investor: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
        lastScore: bigint;
        lastAuditHash: string;
        lastUpdateTimestamp: bigint;
        governanceMode: bigint;
        totalInvested: bigint;
        totalPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgreementScore"
  ): TypedContractMethod<[_agreementId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaymentRecord"
  ): TypedContractMethod<
    [_paymentId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        agreementId: bigint;
        producer: string;
        investor: string;
        amount: bigint;
        auditHash: string;
        score: bigint;
        timestamp: bigint;
        hcsTransactionId: string;
        hfsFileId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "investInAgreement"
  ): TypedContractMethod<[_agreementId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "oracleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        agreementId: bigint;
        producer: string;
        investor: string;
        amount: bigint;
        auditHash: string;
        score: bigint;
        timestamp: bigint;
        hcsTransactionId: string;
        hfsFileId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordAudit"
  ): TypedContractMethod<[_auditHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordAuditV3"
  ): TypedContractMethod<
    [_auditHash: BytesLike, _hcsTransactionId: string, _hfsFileId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestPayment"
  ): TypedContractMethod<
    [_agreementId: BigNumberish, _auditHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFinancialManager"
  ): TypedContractMethod<
    [_financialManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracleManager"
  ): TypedContractMethod<[_oracleManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTechnicalManager"
  ): TypedContractMethod<
    [_technicalManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitValidatedBatch"
  ): TypedContractMethod<
    [_agreementId: BigNumberish, _auditHash: BytesLike, _score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "technicalManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawExcessHBAR"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuditRecorded"
  ): TypedContractEvent<
    AuditRecordedEvent.InputTuple,
    AuditRecordedEvent.OutputTuple,
    AuditRecordedEvent.OutputObject
  >;
  getEvent(
    key: "AuditRecordedV3"
  ): TypedContractEvent<
    AuditRecordedV3Event.InputTuple,
    AuditRecordedV3Event.OutputTuple,
    AuditRecordedV3Event.OutputObject
  >;
  getEvent(
    key: "GovernanceModeChanged"
  ): TypedContractEvent<
    GovernanceModeChangedEvent.InputTuple,
    GovernanceModeChangedEvent.OutputTuple,
    GovernanceModeChangedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentReceived"
  ): TypedContractEvent<
    InvestmentReceivedEvent.InputTuple,
    InvestmentReceivedEvent.OutputTuple,
    InvestmentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentApproved"
  ): TypedContractEvent<
    PaymentApprovedEvent.InputTuple,
    PaymentApprovedEvent.OutputTuple,
    PaymentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRequested"
  ): TypedContractEvent<
    PaymentRequestedEvent.InputTuple,
    PaymentRequestedEvent.OutputTuple,
    PaymentRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatedBatchSubmitted"
  ): TypedContractEvent<
    ValidatedBatchSubmittedEvent.InputTuple,
    ValidatedBatchSubmittedEvent.OutputTuple,
    ValidatedBatchSubmittedEvent.OutputObject
  >;

  filters: {
    "AgreementCreated(uint256,bytes32,address,address,uint256,uint256,uint8)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AuditRecorded(bytes32,uint256)": TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;
    AuditRecorded: TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;

    "AuditRecordedV3(bytes32,uint256,string,string)": TypedContractEvent<
      AuditRecordedV3Event.InputTuple,
      AuditRecordedV3Event.OutputTuple,
      AuditRecordedV3Event.OutputObject
    >;
    AuditRecordedV3: TypedContractEvent<
      AuditRecordedV3Event.InputTuple,
      AuditRecordedV3Event.OutputTuple,
      AuditRecordedV3Event.OutputObject
    >;

    "GovernanceModeChanged(uint256,uint8,uint8)": TypedContractEvent<
      GovernanceModeChangedEvent.InputTuple,
      GovernanceModeChangedEvent.OutputTuple,
      GovernanceModeChangedEvent.OutputObject
    >;
    GovernanceModeChanged: TypedContractEvent<
      GovernanceModeChangedEvent.InputTuple,
      GovernanceModeChangedEvent.OutputTuple,
      GovernanceModeChangedEvent.OutputObject
    >;

    "InvestmentReceived(uint256,address,uint256,uint256)": TypedContractEvent<
      InvestmentReceivedEvent.InputTuple,
      InvestmentReceivedEvent.OutputTuple,
      InvestmentReceivedEvent.OutputObject
    >;
    InvestmentReceived: TypedContractEvent<
      InvestmentReceivedEvent.InputTuple,
      InvestmentReceivedEvent.OutputTuple,
      InvestmentReceivedEvent.OutputObject
    >;

    "PaymentApproved(uint256,address,bytes32,address,uint256,uint256,string,string)": TypedContractEvent<
      PaymentApprovedEvent.InputTuple,
      PaymentApprovedEvent.OutputTuple,
      PaymentApprovedEvent.OutputObject
    >;
    PaymentApproved: TypedContractEvent<
      PaymentApprovedEvent.InputTuple,
      PaymentApprovedEvent.OutputTuple,
      PaymentApprovedEvent.OutputObject
    >;

    "PaymentExecuted(uint256,uint256,address,uint256,string,string)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PaymentRequested(uint256,address,uint256,bytes32)": TypedContractEvent<
      PaymentRequestedEvent.InputTuple,
      PaymentRequestedEvent.OutputTuple,
      PaymentRequestedEvent.OutputObject
    >;
    PaymentRequested: TypedContractEvent<
      PaymentRequestedEvent.InputTuple,
      PaymentRequestedEvent.OutputTuple,
      PaymentRequestedEvent.OutputObject
    >;

    "ValidatedBatchSubmitted(uint256,address,bytes32,uint256,uint256)": TypedContractEvent<
      ValidatedBatchSubmittedEvent.InputTuple,
      ValidatedBatchSubmittedEvent.OutputTuple,
      ValidatedBatchSubmittedEvent.OutputObject
    >;
    ValidatedBatchSubmitted: TypedContractEvent<
      ValidatedBatchSubmittedEvent.InputTuple,
      ValidatedBatchSubmittedEvent.OutputTuple,
      ValidatedBatchSubmittedEvent.OutputObject
    >;
  };
}
