/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PESContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agreementCounter"
      | "agreements"
      | "createAgreement"
      | "deactivateAgreement"
      | "getAgreement"
      | "owner"
      | "recordAudit"
      | "relayer"
      | "requestPayment"
      | "setRelayer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementCreated"
      | "AuditRecorded"
      | "PaymentRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agreementCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAudit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestPayment",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agreementCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAudit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    agreementHash: BytesLike,
    producer: AddressLike,
    baseValue: BigNumberish,
    hectares: BigNumberish
  ];
  export type OutputTuple = [
    agreementId: bigint,
    agreementHash: string,
    producer: string,
    baseValue: bigint,
    hectares: bigint
  ];
  export interface OutputObject {
    agreementId: bigint;
    agreementHash: string;
    producer: string;
    baseValue: bigint;
    hectares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditRecordedEvent {
  export type InputTuple = [auditHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [auditHash: string, timestamp: bigint];
  export interface OutputObject {
    auditHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRequestedEvent {
  export type InputTuple = [
    agreementId: BigNumberish,
    producer: AddressLike,
    amount: BigNumberish,
    auditHash: BytesLike
  ];
  export type OutputTuple = [
    agreementId: bigint,
    producer: string,
    amount: bigint,
    auditHash: string
  ];
  export interface OutputObject {
    agreementId: bigint;
    producer: string;
    amount: bigint;
    auditHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PESContract extends BaseContract {
  connect(runner?: ContractRunner | null): PESContract;
  waitForDeployment(): Promise<this>;

  interface: PESContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agreementCounter: TypedContractMethod<[], [bigint], "view">;

  agreements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        agreementHash: string;
        producer: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  createAgreement: TypedContractMethod<
    [
      _agreementHash: BytesLike,
      _producer: AddressLike,
      _baseValue: BigNumberish,
      _hectares: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deactivateAgreement: TypedContractMethod<
    [_agreementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgreement: TypedContractMethod<
    [_agreementId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        agreementHash: string;
        producer: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordAudit: TypedContractMethod<
    [_auditHash: BytesLike],
    [void],
    "nonpayable"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  requestPayment: TypedContractMethod<
    [_agreementId: BigNumberish, _auditHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agreementCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        agreementHash: string;
        producer: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      _agreementHash: BytesLike,
      _producer: AddressLike,
      _baseValue: BigNumberish,
      _hectares: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateAgreement"
  ): TypedContractMethod<[_agreementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgreement"
  ): TypedContractMethod<
    [_agreementId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        agreementHash: string;
        producer: string;
        baseValue: bigint;
        hectares: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAudit"
  ): TypedContractMethod<[_auditHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestPayment"
  ): TypedContractMethod<
    [_agreementId: BigNumberish, _auditHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuditRecorded"
  ): TypedContractEvent<
    AuditRecordedEvent.InputTuple,
    AuditRecordedEvent.OutputTuple,
    AuditRecordedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRequested"
  ): TypedContractEvent<
    PaymentRequestedEvent.InputTuple,
    PaymentRequestedEvent.OutputTuple,
    PaymentRequestedEvent.OutputObject
  >;

  filters: {
    "AgreementCreated(uint256,bytes32,address,uint256,uint256)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "AuditRecorded(bytes32,uint256)": TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;
    AuditRecorded: TypedContractEvent<
      AuditRecordedEvent.InputTuple,
      AuditRecordedEvent.OutputTuple,
      AuditRecordedEvent.OutputObject
    >;

    "PaymentRequested(uint256,address,uint256,bytes32)": TypedContractEvent<
      PaymentRequestedEvent.InputTuple,
      PaymentRequestedEvent.OutputTuple,
      PaymentRequestedEvent.OutputObject
    >;
    PaymentRequested: TypedContractEvent<
      PaymentRequestedEvent.InputTuple,
      PaymentRequestedEvent.OutputTuple,
      PaymentRequestedEvent.OutputObject
    >;
  };
}
